package com.example.laboratorio.vistas;

import com.example.laboratorio.dao.DaoDistribuidor;
import com.example.laboratorio.dao.impl.DaoDistribuidorImpl;
import com.example.laboratorio.entidades.Distribuidor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PrincipalFrame extends javax.swing.JFrame {

    private DaoDistribuidor daoDistribuidor;
    private Distribuidor distribuidor;
    private DefaultTableModel modeloDist;
    private String opcion;

    public PrincipalFrame() {
        daoDistribuidor = new DaoDistribuidorImpl();
        distribuidor = new Distribuidor();
        modeloDist = new DefaultTableModel();
        initComponents();
        modeloDist.addColumn("ID");
        modeloDist.addColumn("Nombre");
        tablaDistribuidor.setModel(modeloDist);
        listado();
        habilitar(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        distribuidorPanel = new javax.swing.JPanel();
        txt_dist_nombre = new javax.swing.JTextField();
        btn_dist_confirmar = new javax.swing.JButton();
        btn_dist_cancelar = new javax.swing.JButton();
        btn_dist_agregar = new javax.swing.JButton();
        btn_dist_editar = new javax.swing.JButton();
        btn_dist_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDistribuidor = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        videojuegoPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        label4 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblconsulta = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        distribuidorPanel.setBackground(new java.awt.Color(51, 153, 255));

        txt_dist_nombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre del distribuidor"));
        txt_dist_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dist_nombreActionPerformed(evt);
            }
        });

        btn_dist_confirmar.setText("Confirmar");
        btn_dist_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dist_confirmarActionPerformed(evt);
            }
        });

        btn_dist_cancelar.setText("Cancelar");

        btn_dist_agregar.setText("Agregar");
        btn_dist_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dist_agregarActionPerformed(evt);
            }
        });

        btn_dist_editar.setText("Editar");
        btn_dist_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dist_editarActionPerformed(evt);
            }
        });

        btn_dist_eliminar.setText("Eliminar");
        btn_dist_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dist_eliminarActionPerformed(evt);
            }
        });

        tablaDistribuidor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDistribuidor);

        jButton1.setText("PersonalMedico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout distribuidorPanelLayout = new javax.swing.GroupLayout(distribuidorPanel);
        distribuidorPanel.setLayout(distribuidorPanelLayout);
        distribuidorPanelLayout.setHorizontalGroup(
            distribuidorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(distribuidorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(distribuidorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_dist_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(distribuidorPanelLayout.createSequentialGroup()
                        .addComponent(btn_dist_confirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_dist_cancelar)))
                .addGroup(distribuidorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(distribuidorPanelLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addGroup(distribuidorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_dist_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_dist_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(distribuidorPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(86, 86, 86)
                        .addComponent(btn_dist_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, distribuidorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        distribuidorPanelLayout.setVerticalGroup(
            distribuidorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(distribuidorPanelLayout.createSequentialGroup()
                .addGroup(distribuidorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(distribuidorPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txt_dist_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(distribuidorPanelLayout.createSequentialGroup()
                        .addGroup(distribuidorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(distribuidorPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btn_dist_agregar))
                            .addGroup(distribuidorPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_dist_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(distribuidorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_dist_eliminar)
                            .addComponent(btn_dist_cancelar)
                            .addComponent(btn_dist_confirmar))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Proveedores", distribuidorPanel);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Producto");

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Entrada");

        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Salida");

        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Consulta Stock");

        btn1.setText("Actualizar");

        btn2.setText("Eliminar");

        jButton3.setText("Editar");

        btn3.setText("Modificar");

        btn5.setText("Salir");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn4.setText("Agregar");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel2)))
                                .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(label4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addComponent(txt2)
                                .addComponent(txt3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(473, 473, 473)
                        .addComponent(jButton3)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btn4)
                .addGap(34, 34, 34)
                .addComponent(btn5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(btn2)
                    .addComponent(btn3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4)
                    .addComponent(btn5))
                .addGap(62, 62, 62)
                .addComponent(jButton3))
        );

        tblconsulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        tblconsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Entrada", "Salida", "Producto", "Consutla Stock"
            }
        ));
        jScrollPane2.setViewportView(tblconsulta);

        javax.swing.GroupLayout videojuegoPanelLayout = new javax.swing.GroupLayout(videojuegoPanel);
        videojuegoPanel.setLayout(videojuegoPanelLayout);
        videojuegoPanelLayout.setHorizontalGroup(
            videojuegoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videojuegoPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        videojuegoPanelLayout.setVerticalGroup(
            videojuegoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videojuegoPanelLayout.createSequentialGroup()
                .addGroup(videojuegoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(videojuegoPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(videojuegoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inventario", videojuegoPanel);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dist_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dist_agregarActionPerformed
        opcion = "AGREGAR";
        habilitar(true);
    }//GEN-LAST:event_btn_dist_agregarActionPerformed

    private void btn_dist_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dist_confirmarActionPerformed
        String nombre = txt_dist_nombre.getText();
        distribuidor.setNombre(nombre);

        switch (opcion) {
            case "AGREGAR" -> {
                try {
                    daoDistribuidor.insertar(distribuidor);
                    listado();
                    limpiar();
                    habilitar(false);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, daoDistribuidor.getMensaje());
                }
            }
            case "EDITAR" -> {
                try {
                    daoDistribuidor.actualizar(distribuidor);
                    listado();
                    limpiar();
                    habilitar(false);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, daoDistribuidor.getMensaje());
                }
            }
        }
    }//GEN-LAST:event_btn_dist_confirmarActionPerformed

    private void btn_dist_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dist_editarActionPerformed
        if (tablaDistribuidor.getSelectedRow() != -1) {
            opcion = "EDITAR";
            habilitar(true);
            distribuidor.setId(Integer.valueOf(
                    tablaDistribuidor.getValueAt(
                            tablaDistribuidor.getSelectedRow(), 0)
                            .toString())
            );
            txt_dist_nombre.setText(
                    tablaDistribuidor.getValueAt(
                            tablaDistribuidor.getSelectedRow(), 1)
                            .toString()
            );
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Seleccione una fila");

        }


    }//GEN-LAST:event_btn_dist_editarActionPerformed

    private void btn_dist_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dist_eliminarActionPerformed
        if (tablaDistribuidor.getSelectedRow() != -1) {
            try {
                daoDistribuidor.eliminar(
                Integer.valueOf(
                    tablaDistribuidor.getValueAt(
                            tablaDistribuidor.getSelectedRow(), 0)
                            .toString())
                ); 
                limpiar();
                listado();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, daoDistribuidor.getMensaje());
            }
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Seleccione una fila");
        }
    }//GEN-LAST:event_btn_dist_eliminarActionPerformed

    private void txt_dist_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dist_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dist_nombreActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        
           PersonalMedico personalMedico = new PersonalMedico();
            personalMedico.setVisible(true);
        
        
        
    }//GEN-LAST:event_btn4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn_dist_agregar;
    private javax.swing.JButton btn_dist_cancelar;
    private javax.swing.JButton btn_dist_confirmar;
    private javax.swing.JButton btn_dist_editar;
    private javax.swing.JButton btn_dist_eliminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel distribuidorPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label4;
    private javax.swing.JTable tablaDistribuidor;
    private javax.swing.JTable tblconsulta;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt_dist_nombre;
    private javax.swing.JPanel videojuegoPanel;
    // End of variables declaration//GEN-END:variables

    private void listado() {
        //Limpiar la tabla
        modeloDist.setRowCount(0);
        if (daoDistribuidor.selectTodo() == null) {
            return;
        }
        for (Distribuidor dist : daoDistribuidor.selectTodo()) {
            Object[] fila = new Object[2];
            fila[0] = dist.getId();
            fila[1] = dist.getNombre();
            modeloDist.addRow(fila);
        }
    }

    private void habilitar(boolean b) {
        txt_dist_nombre.setEnabled(b);
        btn_dist_confirmar.setEnabled(b);
        btn_dist_cancelar.setEnabled(b);

        btn_dist_agregar.setEnabled(!b);
        btn_dist_editar.setEnabled(!b);
        btn_dist_eliminar.setEnabled(!b);
    }

    private void limpiar() {
        txt_dist_nombre.setText(null);
        opcion = "";
    }
}
